name: Lighthouse CI for Netlify sites
on: [push]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Wait for Netlify Deploy
        uses: kamranayub/wait-for-netlify-action@v2.1.1
        id: waitForDeployment
        with:
          site_id: 'gareth-ferguson'
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ steps.waitForDeployment.outputs.url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
